# Graphwar Plus++ Functions Configuration
# Format: function_name,alias(parameters)=expression|default_values
# Example: rtl,kink(k,c,a)=k/(1+exp(-a*(x+c)))|a=67

台阶,s,step(k,c,a)=k/(1+exp(-a*(x-c)))|a=67
# 1. 台阶
# c:时间
# a:陡峭程度
# k:高度


尖峰,q,sqr(k,c,a)=k/(1+(a(x-c))^2)|a=67
# 2. 尖峰
# k:高度
# c:时间
# a:陡峭程度


sin台阶,p,ssin,stepsin(b,k,c,a)=bsin(kx)/(1+exp(-a*(x-c)))|a=67
# 3. 同1,在c时间开始应用sin
# b是高度

定向sin,d,dirsin(k,c,b)=bsin(cx)/(1+exp(67*(x+k)))
# 4.

斜,t,xie(b,c,a)=a(abs(x-b)-abs(x-c))
# 5. 斜着走
# a:倾斜程度
# b:开始应用的时间
# c:结束应用的时间

神人函数,sr(a,b,c,d,e,f,g)=g/(b+f^e/f*cx-a)+exp(-a*(x-a/c))
# 6. 神人函数
